### PR TITLE
Merge pull request #2 from SethTisue/version-bumps

### PR DESCRIPTION
**Pull request by SethTisue**
context is https://github.com/lightbend/scala-fortify/issues/158
(Lightbend-only link); we want to use this as our sample of how
to use Fortify with Maven

fyi @jdaggett

### CODE REVIEW

**Comment by SethTisue** [comment]
@jrudolph now that the holiday season has passed, can I interest you in this...?

**Comment by jrudolph** [comment]
> @jrudolph now that the holiday season has passed, can I interest you in this...?

Oops, sure, didn't realize that my input was needed here.

**Comment by jrudolph** [comment]
LGTM

Does the project need more tests or CI or something? I guess if it compiles it's good enough to showcase the issues and demo Fortify support?

**Comment by SethTisue** [comment]
@jrudolph I have CI for the fortify branch in my fork running at https://ci.lightbend.com/view/Fortify/job/akka-http-webgoat/ — it checks that the expected vulnerabilities are found. (and that wouldn't work if the code didn't compile)

but it's not good that the branch only exists in my personal fork.

wdyt, can we add my branch here?

I have some old notes from conversation with @jdaggett that seem to imply the plan was to move this entire repo to the lightbend org instead of the akka org? does that ring a bell? it isn't clear why from the notes. personally, I have no preference between lightbend org or akka org

**Comment by raboof** [comment]
> wdyt, can we add my branch here?

I don't see why not 

> imply the plan was to move this entire repo to the lightbend org instead of the akka org? does that ring a bell?

Not to me

**Comment by jrudolph** [comment]
> wdyt, can we add my branch here?

Please do.

> I have some old notes from conversation with @jdaggett that seem to imply the plan was to move this entire repo to the lightbend org instead of the akka org? does that ring a bell? it isn't clear why from the notes. personally, I have no preference between lightbend org or akka org

In the email exchange from December, you suggested `akka`and Jeremy `lightbend`. I guess in the end it ended up in akka because that's where it was easier to find someone to accept the transfer to akka quickly. Also, for consistency with play where a similar project seems to live at playframework. Both is fine for me as well, so I suggest to keep it here until there's a need to move it around.

**Comment by SethTisue** [comment]
> I suggest to keep it here until there's a need to move it around.

SGTM

>> wdyt, can we add my branch here?
> Please do.

I'll need to be granted access: `remote: Permission to akka/akka-http-webgoat.git denied to SethTisue`

**Comment by jrudolph** [comment]
> I'll need to be granted access: `remote: Permission to akka/akka-http-webgoat.git denied to SethTisue`

I gave you access, but how to organize access to this repo alone might be a future reason to move to the lightbend org.

**Comment by SethTisue** [comment]
thanks! I have now pushed the `fortify` branch here and pointed ci.lightbend.com at it.

**Comment by jrudolph** [comment]
Great, thanks @SethTisue.

**Pull request merged**
